### PR TITLE
Convert README from `rst` to `md`

### LINKED ISSUE #2: `README.rst` -> `README.md`
Could we convert the readme to markdown as is the case for the rest of the organisation's repos? I feel people are much more used to markdown compared to `rst`.

### PR DESCRIPTION
**Pull request by navidcy**
Closes #2.

### CODE REVIEW

**Comment by navidcy** [comment]
@josuemtzmo review?

**Comment by josuemtzmo** [comment]
This won't work in the deployment to a website.

**Comment by navidcy** [comment]
Well, you [had claimed](https://github.com/COSIMA/3D_animations/issues/2#issuecomment-897337598) otherwise before.

Close the PR then.

**Comment by josuemtzmo** [comment]
It would work, but then we need to migrate all the files to `markdown` and it won't be as trivial to use some options in the website deployment.

**Comment by josuemtzmo** [comment]
Sorry for not being clearer before

**Comment by navidcy** [comment]
No worries. Close #2 also then.

**Pull request closed without merging**
